// SPDX-License-Identifier: PMPL-1.0-or-later

//! Polygraph Domain Models — GraphQL & Persistence.
//!
//! This module defines the core data structures used throughout the 
//! fact-checking backend. It utilizes `async_graphql` derive macros 
//! to automatically generate the API schema from these Rust structs.

use async_graphql::{InputObject, SimpleObject};
use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

/// CLAIM: The central entity representing a social media statement.
#[derive(Debug, Clone, Serialize, Deserialize, SimpleObject)]
pub struct Claim {
    pub id: Uuid,
    pub text: String,
    pub platform: Option<String>,
    pub text_hash: String, // Canonical SHA-256 for deduplication
    pub status: ClaimStatus,
}

/// VERDICT: The definitive outcome of a fact-check.
#[derive(Debug, Clone, Serialize, Deserialize, async_graphql::Enum, Copy, PartialEq, Eq)]
pub enum Verdict {
    True,
    MostlyTrue,
    Mixed,
    MostlyFalse,
    False,
    Unverifiable,
}

/// ANALYSIS REPORT: The output of the neurosymbolic verification pipeline.
#[derive(Debug, Clone, Serialize, Deserialize, SimpleObject)]
pub struct VerificationResult {
    pub claim_id: Uuid,
    pub verdict: Verdict,
    pub confidence: f64, // 0.0 to 1.0
    pub explanation: String, // Trace generated by the symbolic stage
    pub credibility_score: f64,
}
